AWSTemplateFormatVersion: "2010-09-09"
Description: "Add Transit Gateway and TG Basic Config"
#Parameters:
#    VPC01:
#        Type: String
#        Description: The vpc to launch the service
#        Default: vpc-ID
#    VPC02:
#        Type: String
#        Description: The vpc to launch the service
#        Default: vpc-ID
Resources:
  InternetALB2: 
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    Properties:
      Name: !Sub "${AWS::StackName}-2"
      Tags: 
        - Key: Name
          Value: "N2SVPC-alb2"
      Scheme: "internet-facing"
      LoadBalancerAttributes: 
        - Key: "deletion_protection.enabled"
          Value: false
        - Key: "idle_timeout.timeout_seconds"
          Value: 60
      SecurityGroups:
        - Fn::ImportValue: !Sub "N2SVPC-ALBSecurityGroup"
      Subnets: 
        - Fn::ImportValue: !Sub "N2SVPC-Public-Subnet-A"
        - Fn::ImportValue: !Sub "N2SVPC-Public-Subnet-B"

  ALBListener2: 
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      DefaultActions: 
        - TargetGroupArn: !Ref TargetGroup2
          Type: forward
      LoadBalancerArn: !Ref InternetALB2
      Port: 80
      Protocol: HTTP

  TargetGroup2: 
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
#      VpcId: {'Fn::ImportValue': !Sub "VPC01"}
      VpcId:
        Fn::ImportValue: !Sub "N2SVPC"
      Name: !Sub "${AWS::StackName}-tg2"
      Protocol: HTTP
      Port: 80
      HealthCheckProtocol: HTTP
      HealthCheckPath: "/ec2meta-webpage/index.php"
      HealthCheckPort: "traffic-port"
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2
      HealthCheckTimeoutSeconds: 5
      HealthCheckIntervalSeconds: 10
      Matcher: 
        HttpCode: 200
      Tags: 
        - Key: Name
          Value: !Sub "${AWS::StackName}-tg2"
      TargetGroupAttributes: 
        - Key: "deregistration_delay.timeout_seconds"
          Value: 300
        - Key: "stickiness.enabled"
          Value: false
        - Key: "stickiness.type"
          Value: lb_cookie
        - Key: "stickiness.lb_cookie.duration_seconds"
          Value: 86400
      TargetType: "ip"      
      Targets:
        - AvailabilityZone: "all"
        - Id: "10.2.21.101"
        - Id: "10.2.21.102"
        - Id: "10.2.22.101"
        - Id: "10.2.22.102"
        - Port: 80
#      VpcId: !Ref VPC02
#        Fn::ImportValue: !Sub "VPC02"